name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          output: sitemap.xml
          include: '*.html'
          exclude: 'README.md'
          base_url: 'https://3a1tr.online'
          
